#cloud-config
#Set HostName , update hostname as required
fqdn: swg.safesquid.local
hostname: swg
prefer_fqdn_over_hostname: true
#Add entry in 127.0.0.1 ${fqdn} in /etc/hosts file. 
manage_etc_hosts: localhost
#Set Timezone and Keyboard layout, Update TimeZone and Keyboard layout as per your locality.
timezone: Asia/Kolkata
keyboard:
  layout: us
#Create users = default users created during deployment process, administrator is admin users created for SafeSquid non-previlaged user, ssquid user created for safesquid service
users:
#Default user Created during deployment process
  - default
runcmd:
#Create Custom LVM  Partitions
    - [ wget, "https://raw.githubusercontent.com/SafeSquid-Github/safesquid_cloud-init/main/scripts/makePartitions.sh", -O, /tmp/makePartitions.sh ]
    - [ bin/bash, /tmp/makePartitions.sh ]
#Setup SafeSquid with all required packages and inital setup.
    - [ wget, "https://raw.githubusercontent.com/SafeSquid-Github/safesquid_cloud-init/main/scripts/makeAppliance.sh", -O, /tmp/makeAppliance.sh ]
    - [ bin/bash, /tmp/makeAppliance.sh ]
#Update && Upgrade packages.
package_update: true
package_upgrade: true
